### ISSUE TITLE
Where to set username and passwod

### ISSUE THREAD

**Issue by YukikazeMua** [Pax1601/DCSOlympus#287]

**Comment by Pax1601** [comment]
Hi, I need more details on your request. Are you referring to a server installation?

**Comment by YukikazeMua** [comment]
Yes, I installed it on the server, and then access to the browser requires authentication, but I can't find the Settings for that

**Comment by YukikazeMua** [comment]
Always connect when you log in

**Comment by YukikazeMua** [comment]
Do I need to put files into /dcs/ ?

**Comment by YukikazeMua** [comment]
![image](https://github.com/Pax1601/DCSOlympus/assets/92007054/03a6168f-d612-4396-9564-867375381979)

**Comment by Pax1601** [comment]
Olympus is still in alpha state, no public release has been created. So if you want to use the software you will need to compile it and install it yourself, what you downloaded is only the source code. If you are interested in being an alpha tester I can send you an invite to our Discord group otherwise you either need to compile and install the software or wait for the first public release :)

**Comment by YukikazeMua** [comment]
I want to become an alpha. How can I do that?
