### ISSUE TITLE
Mig-21 - Loadout names are incorrect

### ISSUE THREAD

**Issue by WoodyXP** [Pax1601/DCSOlympus#510]
A convention we have, is that all the loadouts are named with the payload the unit is carrying.

E.G. 
![image](https://github.com/Pax1601/DCSOlympus/assets/55553527/bc34caba-1b08-4ccf-b416-cc9237c81837)

But the MIG-21 is showing:

![image](https://github.com/Pax1601/DCSOlympus/assets/55553527/7ba44cb5-a0a7-455c-ae6e-2aeadb331082)

**Comment by Tk420634** [comment]
What level of jank are you okay with on this one?  I can pretty easily just rename the names in, https://github.com/Pax1601/DCSOlympus/blob/main/client/public/databases/units/aircraftdatabase.json 

But since I can't compile I can't test it lol.  Not a biggy.  Just, do I need to update them in unitpayloads.lua and payloadroles.json as well?  If so I can do so fairly rapidly later today.

**Comment by WoodyXP** [comment]
We're getting the loadouts via Python scripts, that take them directly from the DCS core mods.

https://github.com/Pax1601/DCSOlympus/tree/main/scripts/python. So exception handling will need to be done over there

**Comment by Tk420634** [comment]
> We're getting the loadouts via Python scripts, that take them directly from the DCS core mods.
> 
> https://github.com/Pax1601/DCSOlympus/tree/main/scripts/python. So exception handling will need to be done over there

Cool, I'll leave it then.  I'm a hack, not a real coder.  Always did hate the fishbeds loadout names.  They're actual garbage.
